[versions]
paper = "1.21.5-R0.1-SNAPSHOT"
guice = "7.0.0"
configurate = "4.2.0"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
guice = { module = "com.google.inject:guice", version.ref = "guice" }
configurate-hocon = { module = "org.spongepowered:configurate-hocon", version.ref = "configurate" }